# Schema for the configuration files of the Exam Spider module.

exam_spider.settings:
  type: config_object
  label: 'Exam Spider settings'
  mapping:
    exam_spider_exam_name:
      type: string
      label: 'Exam Name'
    exam_spider_exam_url:
      type: string
      label: 'Exam URL'
